# Generated by Django 5.1 on 2024-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_national_code_myuser_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default='nooooone', max_length=30),
            preserve_default=False,
        ),
    ]
