# Generated by Django 5.1 on 2024-08-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_adress_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
