# Generated by Django 5.1 on 2024-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_code', models.CharField(max_length=10)),
                ('otp_code', models.CharField(max_length=4)),
            ],
        ),
    ]
