# Generated by Django 5.1 on 2024-08-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_book_borrower_alter_book_donator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='aulter',
            new_name='author',
        ),
    ]
