# Generated by Django 5.1 on 2024-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_aulter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
