# Generated by Django 5.1 on 2024-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Summary',
            field=models.TextField(default='Book summary is not available'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
