# Generated by Django 5.1 on 2024-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Summary',
            field=models.TextField(blank=True, default='Book summary is not available', null=True),
        ),
    ]
