# Generated by Django 5.1 on 2024-08-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
